name: Build image & Deploy to Amazon ECR using OIDC

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1

# OIDC利用の場合に変更した箇所（１）
permissions:
  id-token: write   # OIDC トークン取得に必要
  contents: read    # リポジトリ読み取りに必要

jobs:
  deploy:
    name: Build-and-Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # OIDC利用の場合に変更した箇所（２）
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          # コンテナをビルドし、ECR にpush
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./mysite
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./mysite
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
